version: '3'
services:
  app:
    #image: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5030:5030" 
    volumes:
      - .:/app
    environment:
      - PORT=5030
      - NODE_ENV=development
    command: flask -A app run -h 0.0.0.0 -p 5030
    networks:
      - proxy_default
networks:
  proxy_default:
    external: true