version: '3'
services:
  app:
    image: flask-docker-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:  
      - "5030:5030" 
    volumes:
      - flask_telegram:/app
    environment:
      - PORT=5030
      - FLASK_APP=iot.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: flask -A app run -h 0.0.0.0 -p 5030  --reload --debug
    networks:
      - iot

networks:
  iot:
    external: true
volumes:
  flask_telegram:
  flask_core:
